#!/usr/bin/with-contenv bash
# shellcheck shell=bash

mkdir -p /config/data/database
chown -R abc:abc /config

# Set environment variable so the app knows its data dir
echo "/config" > /run/s6/container_environment/COUCHPOTATO_DATA
